version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-presigned-url"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12g2fd3e65848"
s3_prefix = "s3-presigned-url"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "s3-presigned-url"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12g2fd3e65848"
s3_prefix = "s3-presigned-url"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
